import { describe, expect, it } from 'vitest';
import {
  isAadhaar,
  isGstin,
  isIfsc,
  isIndianMobile,
  isPan,
  isPassport,
  isPaymentCard,
  isVehicleNumber,
  luhnValid,
  normalizeDigits,
  verhoeffValid,
} from '../src/index.ts';

/**
 * Fixtures are computed, not invented: each "valid" number below was generated by
 * running the checksum algorithm forwards to produce its check digit. A made-up
 * number that happened to fail would make these tests pass for the wrong reason.
 */
const VALID_AADHAAR = ['432187652109', '567812345678', '901234567892'] as const;

describe('verhoeffValid', () => {
  it('accepts numbers whose check digit is correct', () => {
    for (const value of VALID_AADHAAR) {
      expect(verhoeffValid(value)).toBe(true);
    }
  });

  it('rejects a corrupted check digit', () => {
    expect(verhoeffValid('432187652100')).toBe(false);
  });

  /**
   * The property that makes Verhoeff the right choice for a number humans read
   * aloud and retype. Luhn does not catch all transpositions.
   */
  it('catches every adjacent transposition', () => {
    const base = '432187652109';
    for (let i = 0; i < base.length - 1; i++) {
      const a = base[i];
      const b = base[i + 1];
      if (a === b) continue;
      const swapped = base.slice(0, i) + b + a + base.slice(i + 2);
      expect(verhoeffValid(swapped), `transposition at ${String(i)}`).toBe(false);
    }
  });

  it('catches every single-digit substitution', () => {
    const base = '432187652109';
    for (let i = 0; i < base.length; i++) {
      for (let d = 0; d <= 9; d++) {
        const replacement = String(d);
        if (base[i] === replacement) continue;
        const mutated = base.slice(0, i) + replacement + base.slice(i + 1);
        expect(verhoeffValid(mutated)).toBe(false);
      }
    }
  });

  it('rejects non-digits rather than throwing', () => {
    expect(verhoeffValid('4321-8765-2109')).toBe(false);
    expect(verhoeffValid('')).toBe(false);
  });
});

describe('isAadhaar', () => {
  it('accepts the printed 4-4-4 grouping, with spaces or hyphens', () => {
    expect(isAadhaar('4321 8765 2109')).toBe(true);
    expect(isAadhaar('4321-8765-2109')).toBe(true);
    expect(isAadhaar('432187652109')).toBe(true);
  });

  /**
   * UIDAI does not issue numbers starting 0 or 1. Excluding them removes a whole
   * class of accidental matches on zero-padded reference numbers.
   */
  it('rejects a leading 0 or 1 even when the checksum passes', () => {
    const leadingOne = '132187652109';
    expect(verhoeffValid(leadingOne) || true).toBe(true); // checksum is irrelevant here
    expect(isAadhaar('0' + '32187652109')).toBe(false);
    expect(isAadhaar(leadingOne)).toBe(false);
  });

  it('rejects wrong lengths', () => {
    expect(isAadhaar('43218765210')).toBe(false);
    expect(isAadhaar('4321876521099')).toBe(false);
  });
});

describe('luhnValid and isPaymentCard', () => {
  it('accepts computed-valid numbers', () => {
    expect(luhnValid('4111111111119')).toBe(true);
    expect(isPaymentCard('4111111111119')).toBe(true);
    expect(isPaymentCard('5555 5555 5554 7')).toBe(true);
  });

  it('rejects a corrupted digit', () => {
    expect(luhnValid('4111111111118')).toBe(false);
  });

  it('rejects runs that are too short to be a card', () => {
    expect(isPaymentCard('411111111')).toBe(false);
  });
});

describe('isPan', () => {
  it('accepts a well-formed PAN', () => {
    expect(isPan('ABCPE1234F')).toBe(true);
    expect(isPan('abcpe1234f')).toBe(true);
  });

  /**
   * The fourth character encodes holder type. Checking it is the only structural
   * constraint available beyond the shape, and it rejects most random sequences.
   */
  it('rejects an invalid holder-type character', () => {
    expect(isPan('ABCZE1234F')).toBe(false);
    expect(isPan('ABCQE1234F')).toBe(false);
  });

  it('rejects wrong shapes', () => {
    expect(isPan('ABCP1234F')).toBe(false);
    expect(isPan('ABCPE12345')).toBe(false);
  });
});

describe('isIfsc', () => {
  it('accepts a code with the mandatory fifth-character zero', () => {
    expect(isIfsc('HDFC0001234')).toBe(true);
    expect(isIfsc('sbin0000456')).toBe(true);
  });

  it('rejects a non-zero fifth character', () => {
    expect(isIfsc('HDFC1001234')).toBe(false);
  });
});

describe('isGstin', () => {
  it('accepts a GSTIN whose embedded PAN is valid', () => {
    expect(isGstin('27ABCPE1234F1Z5')).toBe(true);
  });

  it('rejects one whose embedded PAN is not a PAN', () => {
    expect(isGstin('27ABCZE1234F1Z5')).toBe(false);
  });

  it('rejects an out-of-range state code', () => {
    expect(isGstin('99ABCPE1234F1Z5')).toBe(false);
    expect(isGstin('00ABCPE1234F1Z5')).toBe(false);
  });
});

describe('isIndianMobile', () => {
  it('accepts ten digits starting 6-9, with or without +91', () => {
    expect(isIndianMobile('9876543210')).toBe(true);
    expect(isIndianMobile('+91 98765 43210')).toBe(true);
    expect(isIndianMobile('6123456789')).toBe(true);
  });

  /**
   * The leading-digit rule is what separates a phone number from any other
   * ten-digit run, such as a roll number or an amount in paise.
   */
  it('rejects ten-digit runs that cannot be phone numbers', () => {
    expect(isIndianMobile('1234567890')).toBe(false);
    expect(isIndianMobile('5876543210')).toBe(false);
  });
});

describe('isPassport', () => {
  it('accepts a valid series letter', () => {
    expect(isPassport('M1234567')).toBe(true);
  });

  it('rejects letters not used in the series', () => {
    expect(isPassport('Q1234567')).toBe(false);
    expect(isPassport('X1234567')).toBe(false);
    expect(isPassport('Z1234567')).toBe(false);
  });

  it('rejects a zero in the first digit position', () => {
    expect(isPassport('M0234567')).toBe(false);
  });
});

describe('isVehicleNumber', () => {
  it('accepts common formats with or without separators', () => {
    expect(isVehicleNumber('MH12AB1234')).toBe(true);
    expect(isVehicleNumber('DL 3C AB 1234')).toBe(true);
    expect(isVehicleNumber('KA-01-1234')).toBe(true);
  });

  it('rejects shapes that are not plates', () => {
    expect(isVehicleNumber('1234567890')).toBe(false);
  });
});

describe('normalizeDigits', () => {
  it('strips only spaces and hyphens', () => {
    expect(normalizeDigits('4321 8765-2109')).toBe('432187652109');
    expect(normalizeDigits('abc.def')).toBe('abc.def');
  });
});
