// Generated by wxt
import "wxt/browser";

declare module "wxt/browser" {
  export type PublicPath =
    | ""
    | "/"
    | "/background.js"
    | "/content-scripts/content.js"
    | "/icon/128.png"
    | "/icon/16.png"
    | "/icon/32.png"
    | "/icon/48.png"
    | "/icon/96.png"
    | "/models/Xenova/owlvit-base-patch32/config.json"
    | "/models/Xenova/owlvit-base-patch32/merges.txt"
    | "/models/Xenova/owlvit-base-patch32/onnx/model_quantized.onnx"
    | "/models/Xenova/owlvit-base-patch32/onnx/model_quantized.onnx_data"
    | "/models/Xenova/owlvit-base-patch32/onnx/model_quantized.onnx_data_1"
    | "/models/Xenova/owlvit-base-patch32/preprocessor_config.json"
    | "/models/Xenova/owlvit-base-patch32/special_tokens_map.json"
    | "/models/Xenova/owlvit-base-patch32/tokenizer_config.json"
    | "/models/Xenova/owlvit-base-patch32/tokenizer.json"
    | "/models/Xenova/owlvit-base-patch32/vocab.json"
    | "/sidepanel.html"
    | "/tesseract/eng.traineddata.gz"
    | "/tesseract/LICENSE-tesseract-core.txt"
    | "/tesseract/tesseract-core-lstm.wasm.js"
    | "/tesseract/tesseract-core-simd-lstm.wasm.js"
    | "/tesseract/worker.min.js"
  type HtmlPublicPath = Extract<PublicPath, `${string}.html`>
  export interface WxtRuntime {
    getURL(path: PublicPath): string;
    getURL(path: `${HtmlPublicPath}${string}`): string;
  }
}
